name: Get and Cache Dependencies
description: Get the dependencies and cache them for later use in other workflows
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash